server:
  servlet:
    context-path: /aiv
  port: ${aiv_port}

spring:
  resources:
    static-locations: classpath:/static/,file:///${aiv_base}/repository/images/
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  datasource:
    url: ${aiv_db_url} # database for aiv schema
    username: ${aiv_db_user}
    password: ${aiv_db_password} 
    driverClassName: org.postgresql.Driver
  datasource1:
    url: ${security_db_url} # database for security schema
    username: ${security_db_user}
    password: ${security_db_password} 
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
      ddl-auto: update
  liquibase:
   aiv:
     enabled: true
     change-log: classpath:db/changelog/db.changelog-aiv.sql
   security:
     enabled: false
     change-log: classpath:db/changelog/db.changelog-security.sql

# This is normal logging if we missed anything
logging:
  level:
    root: ERROR
security:
  basic:
    path: /basic
    enabled: true
  ignored: /public

#For JNDI Datasources
datasources:
  dslist[0]: '{"jndi-name":"jdbc/ActiveIDB","driver-class-name":"org.postgresql.Driver","url":"${aiv_db_url}","username":"${aiv_db_user}","password":"${aiv_db_password}"}'

#Application some default values
# slatKey -> For stoken decryption SecretKey
# ivspec -> For stoken Iv Spec Key
# securityClass -> which security class we need to use for authentication and user/roles details
# isJira -> Are we using Jira authentication or not
app:
  slatKey: 0123456789abcdef
  ivspec: fedcba9876543210
  imgLocation: ${aiv_base}/repository/images/
  repositoryLocation: ${aiv_base}/repository
  logDir: ${aiv_base}/logs
  deliveryLocation: ${aiv_base}/repository/delivery
  database: postgresql
  securityClass: com.utility.JiraAuthImpl #com.simple.services.SimpleAuthImpl/com.utility.JiraAuthImpl
  isJira: true
  logs:
    jsonlogs: true
    showdept: true
    showtraceid: true
    
#While creating Embed token
# ekey -> Generating Embed Encrypted insternal token.
# tokenKey -> For generating Embed authentication token
embed:
  ekey: ActiveInteigence
  tokenKey: H0WWWrNDCCoVKVPXMSei9/+rDJcLbgkEOXhayw790lY=
  
  
# Token used for MicroServices Internal Authentication 
aiv-internalToken: ActiveIntelligence

# Default Jndi connnection Datasources
external.db.1: jdbc,mysql,ClassicModels,true,java:comp/env/jdbc/classicmodels
#external.db.2: olap,SampleData,mondrian.olap4j.MondrianOlap4jDriver,jdbc:mondrian:DataSource,D:/Repositories/AIV/tomcat/data/sampledata.mondrian.xml,true,org.hsqldb.jdbcDriver,java:comp/env/jdbc/SampleData


#Jira realted configuration
addon.base-url: ${addon_base_url}
com.atlassian.jira.clickjacking.protection.disabled: true
jira.security.csp.sandbox.disabled: true
logging.level.com.atlassian.connect.spring: DEBUG
atlassian.connect.require-auth-include-paths: /v5/ #jpa:  #properties: #hibernate: # default_schema: Default
com.atlassian.jira.clickjacking.protection.exclude: /execute_adhoc_report
atlassian_url: ${atlassian_url}
jira.driver-class-name: org.postgresql.Driver
jira.url: ${jira_db_url}
jira.username: ${jira_db_user}
jira.password: ${jira_db_password}
jira.type_database: postgresql
jira.protocol: jdbc
jiraAdminRoles: administrators,atlassian-addons-admin,site-admins,system-administrators


# Temporary location
general:
  location: ${aiv_base}/repository/Econfig
